backend/controllers/TranslateController.php
<?php

namespace backend\controllers;

use common\helpers\BaseController;
use Yii;
use common\models\helper\Translate;
use backend\models\TranslateSearch;
use yii\base\Exception;
use yii\filters\AccessControl;
use yii\helpers\FileHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use ZipArchive;

/**
 * TranslateController implements the CRUD actions for Translate model.
 */
class TranslateController extends BaseController
{
    public function beforeAction($action)
    {
        Yii::$app->session->set('active_menu_item_sidebar', 'translate');
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        $behaviors = parent::behaviors();

        $behaviors['access']['rules'][1]['actions'][] = 'generate-translate-zip';
        return $behaviors;
    }

    /**
     * Lists all Translate models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TranslateSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Translate model.
     * @param int $id ID
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Translate model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Translate();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Translate model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Translate model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * @throws Exception
     */
    public function actionGenerateTranslateZip()
    {

        $zipFilename = 'main.zip';
        $zipPath = Yii::getAlias('@webroot/' . $zipFilename);

        $zip = new ZipArchive();
        $folders = ['uz', 'ru', 'oz', 'qr'];
        if ($zip->open($zipPath, ZipArchive::CREATE) === true) {
            foreach ($folders as $folder) {
                $subfolderPath = Yii::getAlias('@webroot/' . $folder);
                FileHelper::createDirectory($subfolderPath);

                $jsonFile = $folder . '/' . $folder . '.json';
                $jsonPath = Yii::getAlias('@webroot/' . $jsonFile);

                $language_title = 'title_'.$folder;

                $translations = Translate::find()->select(['keyword', $language_title])->asArray()->all();
                $result = [];
                foreach ($translations as $row) {
                    $result[$row['keyword']] = $row[$language_title];
                }
                $return_result['translations'] = $result;
                $jsonData = json_encode($return_result, JSON_UNESCAPED_UNICODE);

                file_put_contents($jsonPath, $jsonData);
                $zip->addFile($jsonPath, $jsonFile);

            }

            $zip->close();
            // Download the zip file
            Yii::$app->response->sendFile($zipPath)->send();
            unlink($zipPath); // Delete the zip file from server
            foreach ($folders as $folder) {
                $folder_path = Yii::getAlias('@webroot/' . $folder);
                array_map('unlink', glob("$folder_path/*.*"));
                rmdir($folder_path);
            }
        } else {
            Yii::$app->session->setFlash('error', 'Failed to create zip archive.');
        }
    }

    /**
     * Finds the Translate model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Translate the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Translate::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/translate/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\helper\Translate */
/* @var $form yii\bootstrap4\ActiveForm */
?>

<div class="translate-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'keyword')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'title_uz')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'title_oz')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'title_qr')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'title_ru')->textInput(['maxlength' => true]) ?>

<!--    --><?php //= $form->field($model, 'created_at')->textInput() ?>
<!---->
<!--    --><?php //= $form->field($model, 'creator_id')->textInput() ?>
<!---->
<!--    --><?php //= $form->field($model, 'updated_at')->textInput() ?>
<!---->
<!--    --><?php //= $form->field($model, 'modifier_id')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/translate/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\TranslateSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="row mt-2">
    <div class="col-md-12">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'keyword') ?>

    <?= $form->field($model, 'title_uz') ?>

    <?= $form->field($model, 'title_oz') ?>

    <?= $form->field($model, 'title_qr') ?>

    <?php // echo $form->field($model, 'title_ru') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'creator_id') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'modifier_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

    </div>
    <!--.col-md-12-->
</div>

backend/views/translate/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\helper\Translate */

$this->title = 'Create Translate';
$this->params['breadcrumbs'][] = ['label' => 'Translates', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <?=$this->render('_form', [
                        'model' => $model
                    ]) ?>
                </div>
            </div>
        </div>
        <!--.card-body-->
    </div>
    <!--.card-->
</div>

backend/views/translate/index.php
<?php

use yii\bootstrap4\Alert;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\TranslateSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Translates';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row mb-2">
                        <div class="col-md-12">
                            <?= Html::a('Create Translate', ['create'], ['class' => 'btn btn-success']) ?>
                            <?= Html::a('<i class="fas fa-file-download"></i> Translation Zip', ['translate/generate-translate-zip'],
                                ['class' => 'btn btn-secondary']) ?>
                        </div>
                    </div>

                    <?php Pjax::begin(['id' => 'translate-table-pjax']); ?>

                    <?= GridView::widget([
                        'dataProvider' => $dataProvider,
                        'filterModel' => $searchModel,
                        'columns' => [
                            ['class' => 'yii\grid\SerialColumn'],

                            'id',
                            'keyword',
                            'title_uz',
                            'title_oz',
                            'title_qr',
                            'title_ru',
                            //'created_at',
                            //'creator_id',
                            //'updated_at',
                            //'modifier_id',

                            [
                                'class' => '\backend\helper\ActionColumnCustom',
                                'template' => '{view} {update_translate} {delete}',
                            ],
                        ],
                        'summaryOptions' => ['class' => 'summary mb-2'],
                        'pager' => [
                            'class' => 'yii\bootstrap4\LinkPager',
                        ],
                        'tableOptions' => [
                            'id' => 'translate_index_table',
                            'class' => 'table table-striped table-bordered'
                        ]
                    ]); ?>
                    <?php Pjax::end();?>

                </div>
                <!--.card-body-->
            </div>
            <!--.card-->
        </div>
        <!--.col-md-12-->
    </div>
    <!--.row-->
</div>

backend/views/translate/update.php
<?php

/* @var $this yii\web\View */
/* @var $model common\models\helper\Translate */

$this->title = 'Update Translate: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Translates', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>

<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <?=$this->render('_form', [
                        'model' => $model
                    ]) ?>
                </div>
            </div>
        </div>
        <!--.card-body-->
    </div>
    <!--.card-->
</div>

backend/views/translate/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\helper\Translate */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Translates', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>

<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <p>
                        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
                        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
                            'class' => 'btn btn-danger',
                            'data' => [
                                'confirm' => 'Are you sure you want to delete this item?',
                                'method' => 'post',
                            ],
                        ]) ?>
                    </p>
                    <?= DetailView::widget([
                        'model' => $model,
                        'attributes' => [
                            'id',
                            'keyword',
                            'title_uz',
                            'title_oz',
                            'title_qr',
                            'title_ru',
                            'created_at',
                            [
                                'label' => 'Creator',
                                'value' => function ($model) {
                                    return @$model->creator->fullName;
                                }
                            ],
                            'updated_at',
                            [
                                'label' => 'Modifier',
                                'value' => function ($model) {
                                    return @$model->modifier->fullName;
                                }
                            ],
                        ],
                    ]) ?>
                </div>
                <!--.col-md-12-->
            </div>
            <!--.row-->
        </div>
        <!--.card-body-->
    </div>
    <!--.card-->
</div>