backend/controllers/UserController.php
<?php

namespace backend\controllers;

use backend\models\PositionTitleSearch;
use backend\models\UserPositionLinkSearch;
use backend\models\UserRoleLinkSearch;
use backend\models\UserSearch;
use common\helpers\BaseController;
use common\models\users\User;
use Yii;
use yii\helpers\Url;
use yii\web\NotFoundHttpException;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends BaseController
{

    public function beforeAction($action)
    {
        Yii::$app->session->set('active_menu_item_sidebar', 'users');
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param int $id ID
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView(int $id, int $tab = 1)
    {
        $items = [];

        $items[] =  [
            'label'=>'<i class="fas fa-user"></i> User Info',
            'active'=> $tab == 1,
            'linkOptions'=>['data-url'=>Url::to(["/ajax/get-user-info?id=$id"])]
        ];
        $items[] = [
            'label'=>'<i class="fas fa-user-secret"></i> User Role',
            'active'=> $tab == 2,
            'linkOptions'=>['data-url'=>Url::to(["/ajax/get-user-role?id=$id"])]
        ];
        $items[] = [
            'label'=>'<i class="fas fa-heading"></i> User Position Title',
            'active'=> $tab == 3,
            'linkOptions'=>['data-url'=>Url::to(["/ajax/get-position-title?id=$id"])]
        ];
        $items[] = [
            'label'=>'<i class="fas fa-user-secret"></i> User Position',
            'active'=> $tab == 4,
            'linkOptions'=>['data-url'=>Url::to(["/ajax/get-user-position?id=$id"])]
        ];
        return $this->render('view', [
            'items' => $items,
            'model' => $this->findModel($id),
        ]);
    }

    public function actionViewFull(int $id)
    {
        if (($model = User::findOne($id)) == null) {
            throw new NotFoundHttpException('The requested page does not exist.');
        }

        $searchModelURL = new UserRoleLinkSearch();
        $paramssURL = Yii::$app->request->queryParams;
        $paramssURL['UserRoleLinkSearch']['user_id'] = $id;
        $dataProviderURL = $searchModelURL->search($paramssURL);

        $searchModelUPL = new UserPositionLinkSearch();
        $paramssUPL = Yii::$app->request->queryParams;
        $paramssUPL['UserPositionLinkSearch']['user_id'] = $id;
        $dataProviderUPL = $searchModelUPL->search($paramssUPL);

        $searchModelPT = new PositionTitleSearch();
        $paramssPT = Yii::$app->request->queryParams;
        $paramssPT['PositionTitleSearch']['user_id'] = $id;
        $dataProviderPT = $searchModelPT->search($paramssPT);

        return $this->render('view_full', [
            'model' => $model,
            'dataProviderURL' => $dataProviderURL,
            'dataProviderUPL' => $dataProviderUPL,
            'dataProviderPT' => $dataProviderPT
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();
        $referrer_address = Yii::$app->request->referrer;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if (str_contains($referrer_address, 'view-full')){
                return $this->redirect($referrer_address);
            }
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        $referrer_address = Yii::$app->request->referrer;

        if (str_contains($referrer_address, 'view-full')){
            return $this->redirect($referrer_address);
        }
        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/user/_partials/position-title.php
<?php

use backend\models\PositionTitleSearch;
use common\models\users\PositionTitle;
use common\models\users\User;
use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\bootstrap4\Modal;
use yii\grid\GridView;

/* @var PositionTitleSearch $dataProvider */
/* @var User $model */
?>

    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal_position_title">Create</button>
    <hr>
<?php
echo GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        [
            'attribute' => 'id',
            'enableSorting' => false
        ],
        'user.fullName',
        [
            'attribute' => 'title_oz',
            'enableSorting' => false
        ],
        [
            'attribute' => 'title_uz',
            'enableSorting' => false
        ],
        [
            'attribute' => 'title_qr',
            'enableSorting' => false
        ],
        [
            'attribute' => 'title_ru',
            'enableSorting' => false
        ],
        //'created_at',
        //'creator_id',
        //'updated_at',
        //'modifier_id',

        [
            'class' => '\backend\helper\ActionColumnCustom',
            'template' => '{deletePositionTitle}',
        ],
    ],
    'summaryOptions' => ['class' => 'summary mb-2'],
    'pager' => [
        'class' => 'yii\bootstrap4\LinkPager',
    ]
]);
Modal::begin([
    'title' =>'<h2>Create User Position Title</h2>',
    'id' => 'modal_position_title',
    'size' => 'modal-lg',
]);

?>
<div class="position-link-form">

    <?php $form = ActiveForm::begin([
        'action' => '/position-title/create',
        'method' => 'POST'
    ]); ?>
    <?php
    $model_position_title = new PositionTitle();
    echo $form->field($model_position_title, 'user_id')->hiddenInput(['value' => $model->id])->label(false);
    ?>
    <h6><strong>User: </strong> <?php echo $model->fullName; ?></h6>

    <?= $form->field($model_position_title, 'title_oz')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model_position_title, 'title_uz')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model_position_title, 'title_qr')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model_position_title, 'title_ru')->textInput(['maxlength' => true]) ?>

    <div class="form-group" style="text-align: right;">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
<?php
Modal::end();
?>

backend/views/user/_partials/user-info.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model \common\models\users\User */

?>

<div class="row">
    <div class="col-md-12">
        <p>
            <?= Html::a('Update', ['/user/update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Delete', ['/user/delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => 'Are you sure you want to delete this item?',
                    'method' => 'post',
                ],
            ]) ?>
        </p>
        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                'id',
                'pin',
                'first_name',
                'surname',
                'middle_name',
                'image_path',
                'username',
                'created_at',
                'creator_id',
                'updated_at',
                'modifier_id',
            ],
        ]) ?>
    </div>
</div>

backend/views/user/_partials/user-position.php
<?php

use backend\models\UserPositionLinkSearch;
use common\models\users\User;
use common\models\users\UserPositionLink;
use kartik\select2\Select2;
use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\bootstrap4\Modal;
use yii\grid\GridView;

/* @var UserPositionLinkSearch $dataProvider */
/* @var \common\models\users\User $model */

/* @var $this yii\web\View */
/* @var $searchModel backend\models\UserPositionLinkSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
?>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal_position">Create</button>
<hr>
<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],

        [
            'attribute' => 'id',
            'enableSorting' => false
        ],
        'user.fullName',
        [
            'label' => 'Position',
            'value' => function ($model) {
                return @$model->position->title_oz;
            }
        ],
//        'created_at',
//        'creator_id',
        //'updated_at',
        //'modifier_id',

        [
            'class' => '\backend\helper\ActionColumnCustom',
            'template' => '{deleteUserPositionLink}',
        ],
    ],
    'summaryOptions' => ['class' => 'summary mb-2'],
    'pager' => [
        'class' => 'yii\bootstrap4\LinkPager',
    ]
]);

Modal::begin([
    'title' =>'<h2>Create User Position</h2>',
    'id' => 'modal_position',
    'size' => 'modal-lg',
]);

?>
<div class="user-role-link-form">

    <?php $form = ActiveForm::begin([
        'action' => '/user-position-link/create',
        'method' => 'POST'
    ]); ?>
    <?php
    $model_user_position_link = new UserPositionLink();
    echo $form->field($model_user_position_link, 'user_id')->hiddenInput(['value' => $model->id])->label(false);
    ?>
    <h6><strong>User: </strong> <?php echo $model->fullName; ?></h6>

    <?= $form->field($model_user_position_link, 'position_id')->widget(Select2::class, [
        'data' => $model_user_position_link->getPositionSelect(),
        'options' => [
            'placeholder' => 'Выберите '.$model_user_position_link->getAttributeLabel('position_id')
        ],
        'pluginOptions' => ['allowClear' => true],
    ]); ?>

    <div class="form-group" style="text-align: right;">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
<?php
Modal::end();
?>

backend/views/user/_partials/user-role.php
<?php

use backend\models\UserRoleLinkSearch;
use common\models\users\User;
use common\models\users\UserRoleLink;
use kartik\select2\Select2;
use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\bootstrap4\Modal;
use yii\grid\GridView;

/* @var UserRoleLinkSearch $dataProvider */
/* @var \common\models\users\User $model */
?>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal_role">Create</button>
<hr>
<?php
echo GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        [
            'attribute' => 'id',
            'enableSorting' => false
        ],
        'user.fullName',
        [
            'label' => 'Role',
            'value' => function ($model) {
                return @$model->role->title_oz;
            }
        ],
        [
            'label' => 'Department',
            'value' => function ($model) {
                return @$model->department->title_oz;
            }
        ],
//        'created_at',
        //'creator_id',
        //'updated_at',
        //'modifier_id',

        [
            'class' => '\backend\helper\ActionColumnCustom',
            'template' => '{deleteUserRoleLink}',
        ],
    ],
    'summaryOptions' => ['class' => 'summary mb-2'],
    'pager' => [
        'class' => 'yii\bootstrap4\LinkPager',
    ]
]);

Modal::begin([
    'title' =>'<h2>Create User Role</h2>',
    'id' => 'modal_role',
    'size' => 'modal-lg',
]);

?>
<div class="user-position-link-form">

    <?php $form = ActiveForm::begin([
        'action' => '/user-role-link/create',
        'method' => 'POST'
    ]); ?>
    <?php
        $model_user_link = new UserRoleLink();
        echo $form->field($model_user_link, 'user_id')->hiddenInput(['value' => $model->id])->label(false);
    ?>
        <h6><strong>User: </strong> <?php echo $model->fullName; ?></h6>

    <?= $form->field($model_user_link, 'role_id')->widget(Select2::class, [
        'data' => $model_user_link->getRolesSelect(),
        'options' => [
            'placeholder' => 'Выберите '.$model_user_link->getAttributeLabel('role_id')
        ],
        'pluginOptions' => ['allowClear' => true],
    ]); ?>

    <?= $form->field($model_user_link, 'department_id')->widget(Select2::class, [
        'data' => $model_user_link->getDepartmentsSelect(),
        'options' => [
            'placeholder' => 'Выберите '.$model_user_link->getAttributeLabel('department_id')
        ],
        'pluginOptions' => ['allowClear' => true],
    ]); ?>

    <div class="form-group" style="text-align: right;">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
<?php
Modal::end();